function startup
    % Make MATLAB output compact
    format compact

    % Root folder of the project (where this file lives)
    PLATEROOT = fileparts(mfilename('fullpath'));

    % Subfolders to add
    folders = { ...
        fullfile('input', 'Data'), ...
        fullfile('input', 'DataFun'), ...
        fullfile('src', 'Bspline'), ...
        fullfile('src', 'Comparision'), ...
        fullfile('src', 'Fecundity'), ...
        fullfile('src', 'generalFun'), ...
        fullfile('src', 'GTM'), ...
        fullfile('src', 'Kmeans'), ...
        fullfile('src', 'MarkovProperties'), ...
        fullfile('src', 'Maturity'), ...
        fullfile('src', 'Mortality'), ...
        fullfile('src', 'Recruit'), ...
        fullfile('src', 'simulation'), ...
        fullfile('src', 'Valnerability'), ...
        fullfile('src', 'GTM_Normal'), ...
        fullfile('src', 'GTM_Gamma'), ...
        fullfile('src', 'GTM_Log-Normal'), ...
        fullfile('output', 'Plots'), ...
        fullfile('output', 'Write'), ...
        'main' ...
    };

    % Add folders to MATLAB path
    for i = 1:length(folders)
        addpath(fullfile(PLATEROOT, folders{i}));
    end

    fprintf('Growth Transition Matrix environment initialized.\n');
end
